[package]
name = "dashboard-minus-emacs"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
crossterm = "0.28.1"
lazy_static = "1.5.0"
markdown = "1.0.0-alpha.21"
ratatui = "0.29.0"
regex = "1.11.1"
thiserror = "2.0.5"
